language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: V/KWFOAML8+hOHpyP0C3UJpukW/FZJR/AtyYudUxUr3FdHVLx7gMPmFhUXEtKt0v4/9Iebd91YMrpCX+1iz+Ozj8vMRLTTqTHyx5rtgn/VCbFE+xUgSIatm7558XZDlHkt0PmiiZFnDJS0iubsKHyX3L9b9XuIKUTrrOlZe+YiE=
  - secure: gpo1GBujLXGHa4WITuBCFuKMpmpKZk4AFMpxVY5+NGE5IU3eP5nFrCfEqa/8NSuuI2UL9+tSgqDRqOQ4yesC2SRbgAjUkVuXQGaSUi5pYk4p2vU6r+0N6QkSKfFeaPPihS8H9x3QvKR1Oe3jbMwka0k7Di6F2eMSJWPk9q5lTIc=
